---
name: Publish Blacklist and GH Page

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  publist-blacklist:
    name: Publish Dnsmasq blacklist
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Prepare gh-pages
        run: |
          ./blacklist-generator.sh
          cp README.md output/README.md
      -
        name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: output